# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-28 15:19
from __future__ import unicode_literals

import core.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20161126_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='alert_regex',
            field=models.CharField(blank=True, default='', help_text="If not empty and an incoming log file matches this regular expression (as in python's re.search), a notification is sent.", max_length=128, validators=[core.models.regex_validator]),
        ),
        migrations.AlterField(
            model_name='check',
            name='allowed_return_codes',
            field=models.CharField(default='0', help_text="Comma-separated list of return codes that are not considered an error for this job. (Default: '0')", max_length=128, validators=[django.core.validators.RegexValidator(message="Numbers, separated by commas. Example: '-1, -2, 3, 4'.", regex='^ *(-? *[0-9]+)( *, *-? *[0-9]+)* *$')]),
        ),
        migrations.AlterField(
            model_name='check',
            name='expected_regex',
            field=models.CharField(blank=True, default='', help_text="If not empty, all incoming logs for this check have to match (as in python's re.search) this regular expression or a notification is sent.", max_length=128, validators=[core.models.regex_validator]),
        ),
        migrations.AlterField(
            model_name='check',
            name='interval',
            field=models.DurationField(default=datetime.timedelta(30), help_text='Format: days hours:minutes:seconds'),
        ),
        migrations.AlterField(
            model_name='check',
            name='name',
            field=models.CharField(help_text='Define an optional prefix to sort your checks.', max_length=64),
        ),
        migrations.AlterField(
            model_name='check',
            name='store_events',
            field=models.DurationField(default=datetime.timedelta(14), help_text='Time after which events are deleted. Format: days hours:minutes:seconds'),
        ),
        migrations.AlterField(
            model_name='checkevent',
            name='event',
            field=models.CharField(choices=[('start', 'Started'), ('finished', 'Finished'), ('log', 'Log Output')], default='finished', max_length=10),
        ),
    ]
